### PR TITLE
fix: security flaw with routes protection

### LINKED ISSUE #414: Security flaw with routes protection
The current plug protecting the routes is only checking if the authenticated user has permissions inside the organization in the `organization_id` parameter, while this does work on all occasions and redirects inside the app, if a malicious user decides to change the `organization_id` parameter to one belonging to an organization that they have priveleges over, the plug authorizes the user. In other words, the object's association with the id parameter is not being checked.

image

#292 Added `AtomicWeb.MismatchError` for this specific reason but currently it doesn't seem to be in use.

### PR DESCRIPTION
**Pull request by joaodiaslobo**
Fixes #414 

image

### CODE REVIEW

File: lib/atomic_web/plugs/verify_association.ex [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        end
+
+      _ ->
+        conn
+    end
+  end
+
+  defp verify_association(entity, conn) do
+    if has_relation?(entity, conn.params["organization_id"]) do
+      conn
```
Comment (MarioRodrigues10) [inline lib/atomic_web/plugs/verify_association.ex:29]:
```suggestion
      conn
      |> send_response(200, "Association verified")
      |> halt()
```

**Review by MarioRodrigues10 — DISMISSED** [review]

File: lib/atomic_web/plugs/verify_association.ex (hunk 1 above)
Comment (joaodiaslobo) [reply lib/atomic_web/plugs/verify_association.ex:29]: This plug is used to authorize page access taking into account the parameters in the connection. Sending a 200 response wouldn't work here, because our goal is to keep the `conn` undisrupted in order to display the page.

image
_(this should show the partner page)_

**Review by MarioRodrigues10 — APPROVED** [review]
